# Generated by Django 5.0.6 on 2024-06-14 17:35

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=' ', upload_to=job.models.image_upload),
            preserve_default=False,
        ),
    ]
