# Generated by Django 5.0.6 on 2024-06-15 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slag',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
