# Generated by Django 5.0.6 on 2024-06-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_job_slag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='slag',
        ),
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
