# Generated by Django 5.0.6 on 2024-06-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
